  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Te60     O74      2.95021       0   0   0           -0.00225 
      2    Te56     O73      3.49610       0   0   0           -0.01770 
      3    Te60     O73      2.10193       0   0   0           -1.64026 
      4    Te60     H75      3.37832       0   0   0           -0.00694 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Te60     O74      2.95021       0   0   0           -0.00224 
      2    Te56     O73      3.49610       0   0   0           -0.01770 
      3    Te60     O73      2.10193       0   0   0           -1.64025 
      4    Te60     H75      3.37832       0   0   0           -0.00693 
