  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Nb10    Se45      2.47456       0   0   0           -1.25010 
      2    Nb15    Se45      2.74013       0   0   0           -0.63509 
      3    Ir19    Se45      2.56392       0   0   0           -0.72683 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Nb10    Se45      2.47456       0   0   0           -1.25227 
      2    Nb15    Se45      2.74013       0   0   0           -0.63709 
      3    Ir19    Se45      2.56392       0   0   0           -0.72417 
