  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Ta11    Se38      2.60975       0   0   0           -1.50978 
      2    Ta15    Se38      2.60966       0   0   0           -1.56618 
      3    Ta16    Se38      2.60976       0   0   0           -1.66039 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Ta11    Se38      2.60975       0   0   0           -1.46967 
      2    Ta15    Se38      2.60966       0   0   0           -1.47109 
      3    Ta16    Se38      2.60976       0   0   0           -1.48357 
