  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Te35    Co11      2.54389       0   0   0           -0.85479 
      2    Te35    Co14      2.54387       0   0   0           -0.85570 
      3    Te35    Co15      2.54368       0   0   0           -0.85584 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Te35    Co11      2.54389       0   0   0           -0.85651 
      2    Te35    Co14      2.54387       0   0   0           -0.85739 
      3    Te35    Co15      2.54368       0   0   0           -0.85698 
