  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1     La4     I32      3.31152       0   0   0           -0.76910 
      2     La5     I32      3.31158       0   0   0           -0.77781 
      3     La8     I32      3.32443       0   0   0           -0.60190 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1     La4     I32      3.31152       0   0   0           -0.76967 
      2     La5     I32      3.31158       0   0   0           -0.78562 
      3     La8     I32      3.32443       0   0   0           -0.60457 
