  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1     Fe3     S54      2.14297       0   0   0           -1.45643 
      2    Fe17     S54      2.14099       0   0   0           -1.42075 
      3    Fe20     S54      2.12802       0   0   0           -1.41442 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1     Fe3     S54      2.14297       0   0   0           -1.46653 
      2    Fe17     S54      2.14099       0   0   0           -1.43020 
      3    Fe20     S54      2.12802       0   0   0           -1.39432 
