  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Nb18    Se42      2.53948       0   0   0           -1.17642 
      2    Nb20    Se42      2.59354       0   0   0           -1.05121 
      3    Ir38    Se42      2.51451       0   0   0           -0.65509 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Nb18    Se42      2.53948       0   0   0           -1.17625 
      2    Nb20    Se42      2.59354       0   0   0           -1.05360 
      3    Ir38    Se42      2.51451       0   0   0           -0.62381 
