  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Se38     O49      1.91611       0   0   0           -2.13207 
      2    Se28     O50      3.47681       0   0   0           -0.01211 
      3    Se38     O50      2.78173       0   0   0            0.00533 
      4    Se28     H51      3.12133       0   0   0           -0.02090 
      5    Se38     H51      3.10558       0   0   0           -0.00796 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Se38     O49      1.91611       0   0   0           -2.13227 
      2    Se28     O50      3.47681       0   0   0           -0.01211 
      3    Se38     O50      2.78173       0   0   0            0.00530 
      4    Se28     H51      3.12133       0   0   0           -0.02091 
      5    Se38     H51      3.10558       0   0   0           -0.00793 
