  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1    Se27     O49      1.91287       0   0   0           -1.90503 
      2    Se27     O50      2.77363       0   0   0           -0.20029 
      3    Se35     O50      3.36272       0   0   0           -0.15834 
      4    Se27     H51      3.08834       0   0   0           -0.31953 
      5    Se33     H51      3.35777       0   0   0           -0.38036 
      6    Se35     H51      3.07203       0   0   0           -0.27119 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1    Se27     O49      1.91287       0   0   0           -1.90430 
      2    Se27     O50      2.77363       0   0   0           -0.20103 
      3    Se35     O50      3.36272       0   0   0           -0.15847 
      4    Se27     H51      3.08834       0   0   0           -0.32084 
      5    Se33     H51      3.35777       0   0   0           -0.38061 
      6    Se35     H51      3.07203       0   0   0           -0.27114 
