  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1     Ag9     O52      3.16638       0   0   0           -0.02446 
      2     Ag9     O53      2.06653       0   0   0           -0.85611 
      3     Ag9     O54      2.35824       0   0   0           -0.40835 
      4     Ag9     O55      2.10837       0   0   0           -0.77405 
      5     Ag9     O56      2.34448       0   0   0           -0.42308 
      6     Ag9     O58      3.17871       0   0   0           -0.02416 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1     Ag9     O52      3.16638       0   0   0           -0.02350 
      2     Ag9     O53      2.06653       0   0   0           -0.87657 
      3     Ag9     O54      2.35824       0   0   0           -0.46367 
      4     Ag9     O55      2.10837       0   0   0           -0.78422 
      5     Ag9     O56      2.34448       0   0   0           -0.47512 
      6     Ag9     O58      3.17871       0   0   0           -0.02354 
