  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  1
      1     Nb9    Se21      2.53948       0   0   0           -1.17537 
      2    Nb10    Se21      2.59354       0   0   0           -1.05344 
      3    Ir19    Se21      2.51451       0   0   0           -0.62284 
  COHP#  atomMU  atomNU     distance     translation      ICOHP (at) eF   for spin  2
      1     Nb9    Se21      2.53948       0   0   0           -1.17200 
      2    Nb10    Se21      2.59354       0   0   0           -1.04899 
      3    Ir19    Se21      2.51451       0   0   0           -0.64107 
